Website/Controllers/ArticleController.cs
using Application.ArticleLikes;
using Application.Articles;
using Domain.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Website.Controllers
{
	[Authorize]
    public class ArticleController : Controller
    {
	    private readonly IReadArticles _articleReader;
	    private readonly IWriteArticleLikes _articleLikeWriter;
		
	    public ArticleController(
			IReadArticles articleReader, 
			IWriteArticleLikes articleLikeWriter)
	    {
		    _articleReader = articleReader;
		    _articleLikeWriter = articleLikeWriter;
	    }

	    public IActionResult Index(int articleId)
        {	        
			var article = _articleReader.GetById(articleId, User.Identity.Name);

            return View(article);            
        }

	    public IActionResult ToggleLike(int articleId)
	    {
			_articleLikeWriter.Toggle(articleId, User.Identity.Name);

		    return RedirectToAction("Index", new { articleId = articleId });
		}
    }
}

Website/Controllers/PublishController.cs
using System.Collections.Generic;
using System.Linq;
using Application.Articles;
using Domain.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ViewModels;

namespace Website.Controllers
{
	[Authorize(Roles = "publisher")]
    public class PublishController : Controller
    {
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly IReadArticles _articleReader;
	    private readonly IWriteArticles _articleWriter;

	    public PublishController(
			UserManager<ApplicationUser> userManager,
			IReadArticles articleReader, 
			IWriteArticles articleWriter)
	    {
		    _articleReader = articleReader;
		    _articleWriter = articleWriter;
		    _userManager = userManager;
	    }

	    public IActionResult Index()
	    {
		    var articles = _articleReader.GetSummariesByUsername(_userManager.GetUserName(User));

            return View(articles);
        }

	    public IActionResult Create()
	    {
		    return View(new ArticleViewModel());
	    }

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(ArticleViewModel article)
		{
			article = _articleWriter.Create(article);

			if (article.ValidationErrors != null && article.ValidationErrors.Any())
			{
				AddErrors(article.ValidationErrors);

				return View(article);
			}

			return RedirectToAction("Index");
		}
		
	    public IActionResult Edit(int articleId)
	    {
		    var article = _articleReader.GetById(articleId);			

		    return View(article);
	    }

	    [HttpPost]
	    [ValidateAntiForgeryToken]
	    public IActionResult Edit(ArticleViewModel article)
	    {
		    article = _articleWriter.Update(article);

		    if (article.ValidationErrors != null && article.ValidationErrors.Any())
		    {
			    AddErrors(article.ValidationErrors);

			    return View(article);
		    }

		    return RedirectToAction("Index");
	    }

	    public IActionResult Delete(int articleId)
	    {
			_articleWriter.Delete(articleId);

		    return RedirectToAction("Index");
		}

		private void AddErrors(IEnumerable<string> errors)
	    {
		    foreach (var error in errors)
		    {
			    ModelState.AddModelError(string.Empty, error);
		    }
	    }
	}
}

Website/Controllers/StatsController.cs
using Application.Stats;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Website.Controllers
{
	[Authorize(Roles = "publisher")]
	public class StatsController : Controller
    {
	    private readonly ICalculateArticleStatistics _articleStatisticsCalculator;

	    public StatsController(ICalculateArticleStatistics articleStatisticsCalculator)
	    {
		    _articleStatisticsCalculator = articleStatisticsCalculator;
	    }

	    public IActionResult Index()
	    {
            return View();
        }

	    public IActionResult ArticleLikes()
	    {
		    var stats = _articleStatisticsCalculator.GetArticleLikesStats();

		    return View(stats);
	    }
	}
}

Website/Views/Shared/_ArticleForm.cshtml
@using Domain.Security
@model ViewModels.ArticleViewModel

@inject UserManager<ApplicationUser> UserManager

<div asp-validation-summary="All" class="text-danger"></div>
	<input asp-for="ArticleId" class="form-control" type="hidden" value="@Model.ArticleId"/>
	<input asp-for="AuthorId" class="form-control" type="hidden" value="@Model.AuthorId" />
	<input asp-for="AuthorUsername" class="form-control" type="hidden" value="@UserManager.GetUserName(User)"/>
	<div class="form-group">
		<label asp-for="Title" class="col-md-2 control-label"></label>
		<div class="col-md-10">
			<input asp-for="Title" class="form-control" value="@Model.Title" />
			<span asp-validation-for="Title" class="text-danger"></span>
		</div>
	</div>
	<div class="form-group">
		<label asp-for="Summary" class="col-md-2 control-label"></label>
		<div class="col-md-10">
			<input asp-for="Summary" class="form-control" value="@Model.Summary" />
			<span asp-validation-for="Summary" class="text-danger"></span>
		</div>
	</div>
	<div class="form-group">
		<label asp-for="Body" class="col-md-2 control-label"></label>
		<div class="col-md-10">
			<textarea asp-for="Body" class="form-control" value="@Model.Body"></textarea>
			<span asp-validation-for="Body" class="text-danger"></span>
		</div>
	</div>
	<div class="form-group">
		<label asp-for="PublishedDate" class="col-md-2 control-label"></label>
		<div class="col-md-10">
			<input asp-for="PublishedDate" type="date" class="form-control" value="@string.Format("{0:yyyy-MM-dd}", Model.PublishedDate)" />
			<span asp-validation-for="PublishedDate" class="text-danger"></span>
		</div>
	</div>

Website/Views/Shared/_Layout.cshtml
@using Domain.Security
@using Microsoft.AspNetCore.Identity

@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

	
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pressford</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
	<environment names="Staging,Production">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
		      asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
		      asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
	@RenderSection("Styles", required: false)
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Pressford</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
				<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
			@if (SignInManager.IsSignedIn(User))
			{
				if (User.IsInRole("publisher"))
				{
					<li><a asp-area="" asp-controller="Publish" asp-action="Index">Manage Articles</a></li>
					<li><a asp-area="" asp-controller="Stats" asp-action="Index">Statistics</a></li>
				}
			}
			</ul>
			@await Html.PartialAsync("_LoginPartial")
		</div>
	</div>
</nav>
<div class="container body-content">
	@RenderBody()
	<hr/>
	<footer>
		<p>&copy; 2017 - Website</p>
	</footer>
</div>

<environment names="Development">
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
	<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
	        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
	        asp-fallback-test="window.jQuery"
	        crossorigin="anonymous"
	        integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
	</script>
	<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
	        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
	        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
	        crossorigin="anonymous"
	        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
	</script>
	<script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", required: false)
</body>
</html>